# Generated by Django 2.2.28 on 2025-03-11 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20250210_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('CourseID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=200, unique=True)),
                ('Name', models.CharField(max_length=200)),
                ('YearEnrolled', models.DateField()),
                ('CurrentYearStudent', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('DateUploaded', models.DateTimeField(auto_now_add=True)),
                ('Topics', models.CharField(max_length=200)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='Documents/')),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Courses')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Students')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Courses')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Students')),
            ],
        ),
        migrations.CreateModel(
            name='EditedNotes',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DateUploaded', models.DateField(auto_now_add=True)),
                ('CourseID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rango.Courses')),
                ('OriginalNote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rango.Note')),
            ],
        ),
    ]
