# Generated by Django 2.2.28 on 2025-03-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_courses_editednotes_enrolls_note_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.AlterField(
            model_name='students',
            name='UserID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
