# Generated by Django 2.2.28 on 2025-03-11 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20250311_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editednotes',
            name='CourseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Courses'),
        ),
        migrations.AlterField(
            model_name='editednotes',
            name='OriginalNote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Note'),
        ),
    ]
