# Generated by Django 2.2.28 on 2025-03-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_auto_20250311_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='YearEnrolled',
            field=models.IntegerField(),
        ),
    ]
