# Generated by Django 2.2.28 on 2025-03-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_auto_20250311_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='Owner',
            new_name='UserID',
        ),
    ]
